GET http://localhost:8880/Ebook/list
Accept: application/json

###

GET http://localhost:8880/Ebook/list?name=Java
Accept: application/json

###

GET http://localhost:8880/Ebook/list?page=1&size=4&name=Java

###

POST http://localhost:8880/Ebook/save
Accept: application/json

###
GET http://localhost:8880/User/list

